### ISSUE TITLE
How to get training data？

### ISSUE THREAD

**Issue by fastcode3d** [SSRSGJYD/NeuralTexture#1]
Thank you very much for your work. 
How can I get the training data?

**Comment by SSRSGJYD** [comment]
There are 2 ways. One way is to render training data, the code is at https://github.com/A-Dying-Pig/OpenGL_NeuralTexture. The other way is to reconstruct from real scene, the code is at https://github.com/gerwang/InfiniTAM .

**Comment by fastcode3d** [comment]
Thank you very much, I will try it.

**Comment by kjzju** [comment]
Thank you for your work. I still don't understand how to get training data. Could you please show some concrete training data examples?

**Comment by SSRSGJYD** [comment]
You can reference to the newly-added README of https://github.com/A-Dying-Pig/OpenGL_NeuralTexture.

**Comment by kjzju** [comment]
Thank you. I'll have a try.

**Comment by CauchyComplete** [comment]
@SSRSGJYD Hi, thank you for your work. It seems that https://github.com/A-Dying-Pig/OpenGL_NeuralTexture github has only two objects to render. Is it enough to train your model? If it is, I'll try it.

**Comment by SSRSGJYD** [comment]
https://github.com/A-Dying-Pig/OpenGL_NeuralTexture is enough to generate training data. It is just a demo code, and you can define new scenes.
