### ISSUE TITLE
Creating UV input data

### ISSUE THREAD

**Issue by davidvfx07** [SSRSGJYD/NeuralTexture#11]
I've looked all over the internet for how to simply render a UV map or "texel-to-pixel mapping" and have found nothing. As mentioned in the README, [OpenGL_NeuralTexture](https://github.com/A-Dying-Pig/OpenGL_NeuralTexture) is an option, but I am hesitant to use that repo because it's kinda messy, most of it is hardcoded and inflexible/unusable, and I couldn't even compile it on Windows.

Is there another way to get the UV input data?

**Comment by davidvfx07** [comment]
I've managed to get UV data from Blender by rendering a UV pass and converting the RG channels to NPY.

**Comment by AnanthK1998** [comment]
hi, could you share a script for this? Thanks in advance. email: ananth1544@gmail.com

**Comment by davidvfx07** [comment]
The following script should work for converting images to NPY files, though I recommend a [fork](https://github.com/DanAmador/NeuralTexture) by [DanAmador ](https://github.com/DanAmador) which allows for the use of PNG files. As for rendering a UV pass, I will differ you to issue [#6](https://github.com/SSRSGJYD/NeuralTexture/issues/6) where I posted a script for rendering [DECA ](https://github.com/yfeng95/DECA) faces to uv maps.

```
import os
import glob
from numpy import save
from matplotlib.image import imread

in_dir = "Input"
out_dir = "Output"

os.makedirs(out_dir, exist_ok=True)

sequence = glob.glob(os.path.join(in_dir, "*"))

for i in range(len(sequence)):
    npy = imread(sequence[i])

    save(os.path.join(out_dir, f"{i:04d}.npy"), npy)
```

**Comment by AnanthK1998** [comment]
Hey, thanks. What I was looking for is, given a single OBJ file of an object. I want to render in multiple views, and generate UV images for those views as well. I am not using a sequence of objs. Thanks a lot in advance.
